# Base configs
baseurl: "https://gandalf1819.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Chinmay Wyawahare"
subtitle: "See the world through my eyes!"
author: "Chinmay Wyawahare"
header:
 title: "Photography"
 subtitle: "by Chinmay Wyawahare"
footer:
 name: "Hey there, my name is Chinmay"
 bio: "I am a developer and a graduate student at New York University and currently pursuing my Master of Science Degree in Computer Science. This my portfolio for photography."
 github: "https://github.com/gandalf1819"
web_design: "CW"
social_urls:
  instagram: "https://www.instagram.com/wyavs"
  linkedin: "https://www.linkedin.com/in/chinmaywyawahare/"
  github: "https://www.github.com/gandalf1819"
